resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: docker-proteus-aws-operator-test.dr-uw2.adobeitc.com/proteus-aws-operator
  newTag: v0.0.1
