apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: proteus-aws-operator-manager-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: proteus-aws-operator-manager-role
subjects:
    - kind: ServiceAccount
      name: proteus-aws-operator-controller-manager
      namespace: proteus-aws-operator-system
