# permissions for end users to view dbreplicationgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbreplicationgroup-viewer-role
rules:
- apiGroups:
  - dbreplicationgroups.rds.services.k8s.aws.adobe.io
  resources:
  - dbreplicationgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbreplicationgroups.rds.services.k8s.aws.adobe.io
  resources:
  - dbreplicationgroups/status
  verbs:
  - get
