# permissions for end users to view dbusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbuser-viewer-role
rules:
- apiGroups:
  - rds.services.k8s.aws.adobe.io
  resources:
  - dbusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rds.services.k8s.aws.adobe.io
  resources:
  - dbusers/status
  verbs:
  - get
