## Append samples you want in your CSV to this file as resources ##
resources:
- dbreplicationgroups.rds.services.k8s.aws_v1alpha1_dbreplicationgroup.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
