## Append samples you want in your CSV to this file as resources ##
resources:
- rds.services.k8s.aws.adobe.io_v1alpha1_dbreplicationgroup.yaml
- rds.services.k8s.aws.adobe.io_v1alpha1_dbuser.yaml
- rds_v1alpha1_dbuser.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
