apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBCluster
metadata:
  name: {{.Values.DB_CLUSTER_ID}}-DBUser-Aurora
spec:
  availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1e
  dbClusterIdentifier: {{.Values.DB_CLUSTER_ID}}-DBUser-Aurora
  dbName: {{.Values.DB_NAME}}
  engine: aurora-mysql
  masterUsername: root
  masterUserPassword:
    namespace: {{.Values.MASTER_USER_PASS_SECRET_NAMESPACE}}
    name: {{.Values.MASTER_USER_PASS_SECRET_NAME}}
    key: {{.Values.MASTER_USER_PASS_SECRET_KEY}}
---
# Admin user
apiVersion: rds.services.k8s.aws.adobe.io/v1alpha1
kind: DBUser
metadata:
  name: {{.Values.DB_CLUSTER_ID}}-DBUser-Aurora-admin
spec:
  dbClusterIdentifier: {{.Values.DB_CLUSTER_ID}}-DBUser-Aurora
  username: admin 
  useIAMAuthentication: true
  # Note: The RDS Master User (DBCluster.MasterUsername) does not have super user privileges. Thus, you
  #       when you use `GRANT ALL PRIVILEGES ON `%`.* TO ?`, the user will still only be granted certain
  #       privileges.
  #       See: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.MasterAccounts.html
  grantStatement: "GRANT ALL ON `%`.* TO ? REQUIRE SSL"
---
# Application user
apiVersion: rds.services.k8s.aws.adobe.io/v1alpha1
kind: DBUser
metadata:
  name: {{.Values.DB_CLUSTER_ID}}-DBUser-Aurora-application
spec:
  dbClusterIdentifier: {{.Values.DB_CLUSTER_ID}}-DBUser-Aurora
  username: application 
  useIAMAuthentication: true
  grantStatement: "GRANT SELECT, INSERT, UPDATE, DELETE ON `%`.* TO {} REQUIRE SSL"
---
# Reader user
apiVersion: rds.services.k8s.aws.adobe.io/v1alpha1
kind: DBUser
metadata:
  name: {{.Values.DB_CLUSTER_ID}}-DBUser-Aurora-reader
spec:
  dbClusterIdentifier: {{.Values.DB_CLUSTER_ID}}-DBUser-Aurora
  username: reader 
  useIAMAuthentication: true
  grantStatement: "GRANT SELECT ON `%`.* TO {} REQUIRE SSL"
