# DBCluster which creates the Aurora DB Cluster 
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBCluster
metadata:
  name: {{.Values.DB_CLUSTER_ID}}
spec:
  dbClusterIdentifier: {{.Values.DB_CLUSTER_ID}}
  engine: aurora-mysql
  masterUsername: root
  masterUserPassword:
    namespace: {{.Values.MASTER_USER_PASS_SECRET_NAMESPACE}}
    name: {{.Values.MASTER_USER_PASS_SECRET_NAME}}
    key: {{.Values.MASTER_USER_PASS_SECRET_KEY}}
---
# DBReplicationGroup which will create all of the instances (Write/Read)
# Note: AWS Aurora will automatically choose which instance (usually the first) to promote as the Write instance
apiVersion: rds.services.k8s.aws.adobe.io/v1alpha1
kind: DBReplicationGroup
metadata:
  name: {{.Values.DB_CLUSTER_ID}}-DBReplicationGroup
spec:
  numReplicas: 5
  dbInstance:
    dbName: {{.Values.DB_NAME}}
    dbInstanceClass: db.t3.micro
    dbInstanceIdentifier: {{.Values.DB_INSTANCE_ID}}
    dbClusterIdentifier: {{.Values.DB_CLUSTER_ID}}
    engine: aurora-mysql
    masterUsername: root
    masterUserPassword:
      namespace: {{.Values.MASTER_USER_PASS_SECRET_NAMESPACE}}
      name: {{.Values.MASTER_USER_PASS_SECRET_NAME}}
      key: {{.Values.MASTER_USER_PASS_SECRET_KEY}}
