# DBInstance which creates the Write Instance
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: {{.Values.DB_INSTANCE_ID}}-write
spec:
  dbInstanceClass: db.m5.large
  dbInstanceIdentifier: {{.Values.DB_INSTANCE_ID}}-write
  engine: mysql
  masterUsername: root
  masterUserPassword:
    namespace: {{.Values.MASTER_USER_PASS_SECRET_NAMESPACE}}
    name: {{.Values.MASTER_USER_PASS_SECRET_NAME}}
    key: {{.Values.MASTER_USER_PASS_SECRET_KEY}}
---
# DBReplicationGroup which will create the Read Replica Instances
apiVersion: rds.services.k8s.aws.adobe.io/v1alpha1
kind: DBReplicationGroup
metadata:
  name: {{.Values.DB_INSTANCE_ID}}-DBReplicationGroup
spec:
  numReplicas: 5
  dbInstance:
    dbName: {{.Values.DB_NAME}}
    dbInstanceClass: db.m5.large
    dbInstanceIdentifier: {{.Values.DB_INSTANCE_ID}}-read
    engine: mysql
    masterUsername: root
    masterUserPassword:
      namespace: {{.Values.MASTER_USER_PASS_SECRET_NAMESPACE}}
      name: {{.Values.MASTER_USER_PASS_SECRET_NAME}}
      key: {{.Values.MASTER_USER_PASS_SECRET_KEY}}
    sourceDBInstanceIdentifier: {{.Values.DB_INSTANCE_ID}}-write
