apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: {{.Values.DB_INSTANCE_ID}}-DBUser-MySQL
spec:
  dbName: {{.Values.DB_NAME}}
  dbInstanceClass: db.m5.large
  dbInstanceIdentifier: {{.Values.DB_INSTANCE_ID}}-DBUser-MySQL
  engine: mysql
  masterUsername: root
  masterUserPassword:
    namespace: {{.Values.MASTER_USER_PASS_SECRET_NAMESPACE}}
    name: {{.Values.MASTER_USER_PASS_SECRET_NAME}}
    key: {{.Values.MASTER_USER_PASS_SECRET_KEY}}
---
# Admin user
apiVersion: rds.services.k8s.aws.adobe.io/v1alpha1
kind: DBUser
metadata:
  name: {{.Values.DB_INSTANCE_ID}}-DBUser-MySQL-admin
spec:
  dbInstanceIdentifier: {{.Values.DB_INSTANCE_ID}}-DBUser-MySQL
  username: admin 
  useIAMAuthentication: true
  # Note: The RDS Master User (DBInstance.MasterUsername) does not have super user privileges. Thus, you
  #       when you use `GRANT ALL PRIVILEGES ON `%`.* TO ?`, the user will still only be granted certain
  #       privileges.
  #       See: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.MasterAccounts.html
  grantStatement: "GRANT ALL ON `%`.* TO ? REQUIRE SSL"
---
# Application user
apiVersion: rds.services.k8s.aws.adobe.io/v1alpha1
kind: DBUser
metadata:
  name: {{.Values.DB_INSTANCE_ID}}-DBUser-MySQL-application
spec:
  dbInstanceIdentifier: {{.Values.DB_INSTANCE_ID}}-DBUser-MySQL
  username: application 
  useIAMAuthentication: true
  grantStatement: "GRANT SELECT, INSERT, UPDATE, DELETE ON `%`.* TO {} REQUIRE SSL"
---
# Reader user
apiVersion: rds.services.k8s.aws.adobe.io/v1alpha1
kind: DBUser
metadata:
  name: {{.Values.DB_INSTANCE_ID}}-DBUser-MySQL-reader
spec:
  dbInstanceIdentifier: {{.Values.DB_INSTANCE_ID}}-DBUser-MySQL
  username: reader 
  useIAMAuthentication: true
  grantStatement: "GRANT SELECT ON `%`.* TO {} REQUIRE SSL"
