apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBCluster
metadata:
  name: {{.DB_CLUSTER_ID}}_DBUSER
spec:
  availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1e
  dbClusterIdentifier: {{.DB_CLUSTER_ID}}_DBUSER
  databaseName: {{.DB_NAME}}
  engine: aurora-mysql
  masterUsername: root
  masterUserPassword:
    namespace: {{.MASTER_USER_PASS_SECRET_NAMESPACE}}
    name: {{.MASTER_USER_PASS_SECRET_NAME}}
    key: {{.MASTER_USER_PASS_SECRET_KEY}}
---
# Admin user
apiVersion: rds.services.k8s.aws.adobe.io/v1alpha1
kind: DBUser
metadata:
  name: {{.DB_CLUSTER_ID}}_DBUSER_admin
spec:
  dbClusterIdentifier: {{.DB_CLUSTER_ID}}_DBUSER
  engine: mysql
  username: admin 
  useIAMAuthentication: true
  # Note: The RDS Master User (DBCluster.MasterUsername) does not have super user privileges. Thus, you
  #       when you use `GRANT ALL PRIVILEGES ON `%`.* TO ?`, the user will still only be granted certain
  #       privileges.
  #       See: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.MasterAccounts.html
  grantStatement: "GRANT ALL ON `%`.* TO ? REQUIRE SSL"
---
# Application user
apiVersion: rds.services.k8s.aws.adobe.io/v1alpha1
kind: DBUser
metadata:
  name: {{.DB_CLUSTER_ID}}_DBUSER_application
spec:
  dbClusterIdentifier: {{.DB_CLUSTER_ID}}_DBUSER
  engine: mysql
  username: application 
  useIAMAuthentication: true
  grantStatement: "GRANT SELECT, INSERT, UPDATE, DELETE ON `%`.* TO {} REQUIRE SSL"
---
# Reader user
apiVersion: rds.services.k8s.aws.adobe.io/v1alpha1
kind: DBUser
metadata:
  name: {{.DB_CLUSTER_ID}}_DBUSER_reader
spec:
  dbClusterIdentifier: {{.DB_CLUSTER_ID}}_DBUSER
  engine: mysql
  username: reader 
  useIAMAuthentication: true
  grantStatement: "GRANT SELECT, INSERT, UPDATE, DELETE ON `%`.* TO {} REQUIRE SSL"
